GoldOddChest:
  itemstack: ENDER_CHEST,"&6Golden Odd Chest",0
  chance: 25.0
  lootTable:
  - GOLDEN_HELMET,&6Butter Helmet,12,50
  - GOLDEN_BOOTS,&eidk?,11,50 
  
DiamondOddChest:
  itemstack: DIAMOND_BLOCK,"&bDiamond Odd Chest",0
  chance: 10.0
  lootTable:
  - DIAMOND,,0,20
  - COAL,"&8Almost A Diamond",0,80