main: me.ipodtouch0218.oddchestc.OddMain
name: OddChestC
version: 1.1-for-OmegaRaids
author: ipodtouch0218
commands:
   oddchest:
      permission: oddchestc.command
      description: Main OddChestC Command
      usage: /<command> give <player> <chest> <amount>